# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

	topics = Topic.create([
		{ title: 'html5' },
		{ title: 'CSS3' },
		{ title: 'Reponsive Design' },
		{ title: 'Tech Speak' },
		{ title: 'Front vs. Back End' },
		{ title: 'Forms & Embeds' },
		{ title: 'Apple vs. Android' },
		{ title: 'App Lifecycle' },
		{ title: 'Wireframing' },
		{ title: 'Swift' },
		{ title: 'Xcode' },
		{ title: 'Grid Systems' },
		{ title: 'jQuery' },
		{ title: 'Animation' },
		{ title: 'Parallax' },
		{ title: 'Maps' },
		{ title: 'Plugins' },
		{ title: 'Ruby on Rails ' },
		{ title: 'Gems' },
		{ title: 'Content Management' },
		{ title: 'Git' },
		{ title: 'Heroku' },
		{ title: 'Geolocation' },
		{ title: 'Social Login' },
		{ title: 'Payments' },
		{ title: 'Automated Testing' },
		{ title: 'Javascript' },
		{ title: 'Ajax' },
		{ title: 'Api' },
		{ title: 'Control Flow' },
		{ title: 'iOS8' },
		{ title: 'Login' },
		{ title: 'Storyboards' },
		{ title: 'Cocoapods' },
		{ title: 'Camera' },
		{ title: 'App Store' },
		{ title: 'Parse' },
		{ title: 'Command Line' },
		{ title: 'Ruby' },
		{ title: 'Test Driven Development' },
		{ title: 'Object Orientated Programming' },
		{ title: 'Lambda' },
		{ title: 'Procs' },
		{ title: 'Composition' },
		{ title: 'Inheritence' },
		{ title: 'Iterators' },
		{ title: 'Recursion' },
		{ title: 'Http protocols' },
		{ title: 'Sinatra' },
		{ title: 'Html' },
		{ title: 'CSS' },
		{ title: 'Chrome Development Tools' },
		{ title: 'Relational Database' },
		{ title: 'DataMapper' },
		{ title: 'Key Value Stores' },
		{ title: 'SQL' },
		{ title: 'Hashing' },
		{ title: 'Salting' },
		{ title: 'User Management System' },
		{ title: 'Account Security' },
		{ title: 'Capybara' },
		{ title: 'Front End' },
		{ title: 'JavaScript' },
		{ title: 'Responsive design' },
		{ title: 'Angular' },
		{ title: 'Node.js' },
		{ title: 'Ruby on Rails' },
		{ title: 'ActiveRecord' },
		{ title: 'Asset pipeline' },
		{ title: 'Routing' },
		{ title: 'Rails Architecture' },
		{ title: 'Web sockets' },
		{ title: 'HTML5 API' },
		{ title: 'Bootstrap' },
		{ title: 'Foundation' },
		{ title: 'Stripe API' },
		{ title: 'Twilio API' },
		{ title: 'Technical Tests' },
		{ title: 'Open-source Code' },
		{ title: 'MVP' },
		{ title: 'Simple Websites' },
		{ title: 'User Interface' },
		{ title: 'Backend' },
		{ title: 'Programming Theory' },
		{ title: 'App research' },
		{ title: 'App planning' },
		{ title: 'Hacking' },
		{ title: 'Security Problems' },
		{ title: 'Minimise risk' },
		{ title: 'Intro to data' },
		{ title: 'Data Tools' },
		{ title: 'Data Visulisation' },
		{ title: 'Data exploration' },
		{ title: 'Web Architecture' },
		{ title: 'APIs' },
		{ title: 'Social Media monitering' },
		{ title: 'Data queries' },
		{ title: 'Real-time data' },
		{ title: 'Visulisation Strategy' },
		{ title: 'Data Analysis' },
		{ title: 'Scrubbing Data' },
		{ title: 'Communication' },
		{ title: 'Embracing mobile' },
		{ title: 'Internet of Things' },
		{ title: 'Wearable Technology' },
		{ title: 'New technology' },
		{ title: 'Electornic Hardware' },
		{ title: 'Internet connected devices' },
		{ title: 'Physical / Digital' },
		{ title: 'NFC' },
		{ title: 'iBeacons' },
		{ title: 'Sensors' },
		{ title: 'Data Collection' },
		{ title: '3D printing' },
		{ title: 'Laser Cutting' },
		{ title: 'Programming Languages' },
		{ title: 'Data Sources' },
		{ title: 'Prototyping' },
		{ title: 'Digital Leadership' },
		{ title: 'Technical Communication' },
		{ title: 'Web infrastructure' },
		{ title: 'Google Web fonts' },
		{ title: 'Resposive design' },
		{ title: 'Algorithms' },
		{ title: 'Building Behavior' },
		{ title: 'Data Scructure' },
		{ title: 'Loops' },
		{ title: 'Variables' },
		{ title: 'Bug testing' },
		{ title: 'Lesson Planning' }
	])

	organizations = Organization.create([
		{ title: 'Steer' },
		{ title: 'Decoded' },
		{ title: 'Makers Academy' }
	])
